name: Deploy Produção

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, production]

    steps:
      - name: Deploy produção
        run: |
          cd /var/www/tutela
          git fetch origin
          git reset --hard origin/main

          cd /opt/tutela-v2
          docker compose up -d --build