name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy em produção via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.30.220
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /opt/scripts/deploy.sh